### ISSUE TITLE
XLMEUR

### ISSUE THREAD

**Issue by dirtyissa** [ogoossens/CryptoSummary#1]
XLMEUR Is Missing
![image](https://user-images.githubusercontent.com/6024410/29112959-e3260758-7cef-11e7-8330-a847154f2b33.png)

**Comment by ogoossens** [comment]
whats LM?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com

**Comment by dirtyissa** [comment]
![image](https://user-images.githubusercontent.com/6024410/29113462-56760bb2-7cf1-11e7-817b-5523052beee0.png)
https://coinmarketcap.com/currencies/stellar/

Its called XLM in Kraken.
btw if he dosent know the value it has to be ignored.
![image](https://user-images.githubusercontent.com/6024410/29113540-90f733ce-7cf1-11e7-8867-91a38b1aeb46.png)

**Comment by ogoossens** [comment]
ur using XLM? Shall I implement it?

Well the URLs will be build just by the builder by the end of the day so no
need to ignore ... I mean ppl will have just that what I let them to do
with builder :D

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com

**Comment by dirtyissa** [comment]
yes please

**Comment by ogoossens** [comment]
Stellar Lumens <https://coinmarketcap.com/currencies/stellar/> ? :D

wtf

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com
