### ISSUE TITLE
RELOAD

### ISSUE THREAD

**Issue by dirtyissa** [ogoossens/CryptoSummary#2]
Dear DEV,
can we please have a auto refreshing function.
thank you
kr

**Comment by ogoossens** [comment]
Will do in next release :-*

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com

**Comment by ogoossens** [comment]
Added with last commit - timer is on 60 sec


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com

**Comment by dirtyissa** [comment]
works 
![image](https://user-images.githubusercontent.com/6024410/29126971-09a882e0-7d20-11e7-8e8b-93402d1080c2.png)
closing
