### ISSUE TITLE
comma

### ISSUE THREAD

**Issue by dirtyissa** [ogoossens/CryptoSummary#3]
![image](https://user-images.githubusercontent.com/6024410/29120186-7a1499fe-7d09-11e7-8f82-46dd0c7ae04f.png)
there is no need for 10000000 after the comma,
can you please adjust to 3 digit after the comma.

**Comment by ogoossens** [comment]
True that, will implement in next push

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com

**Comment by dirtyissa** [comment]
![image](https://user-images.githubusercontent.com/6024410/29123376-dc548622-7d15-11e7-977f-2c90f32c568b.png)
almost done, only appearing in difference

**Comment by ogoossens** [comment]
done test :P

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Thank you*
*Ďakujem*

*Oliver Goossens*
oliver.goossens@gmail.com

**Comment by dirtyissa** [comment]
works, clsoing issue.
thx
