### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by dirtyissa** [ogoossens/CryptoSummary#4]
![image](https://user-images.githubusercontent.com/6024410/29128999-c03b0104-7d25-11e7-99c1-56599b53ed75.png)

**Comment by ogoossens** [comment]
Try reloading? Working for me atm

**Comment by dirtyissa** [comment]
back running...hmm

**Comment by ogoossens** [comment]
I bet it was the amount of requests you asked for - thats why I need
cashing asap :-/
